# Concatonate All Deseq2 Data with Karri RefGenome Metadata

## <br> 1. Import Required Packages

In [2]:
import numpy as np
import pandas as pd

## <br> 2. Import Deseq2 Data and All Other Metadata

In [3]:
pDREs_Master = pd.read_csv('../../99_mm39_DREs/02_CleanUp_DRE_BED_File/DRE_Counts_by_Gene.txt', 
                            delimiter = '\t')

pDREs_Master = pDREs_Master.dropna()

pDREs_Master = pDREs_Master.rename(columns={'gene_name': 'Gene', 'count': 'pDRE'})

pDREs_Master.head(5)

     Gene  pDRE
1  Spire1    75
2    Wwox    47
3   Apbb2    43
4    Sdk1    38
5   Apoc2    37

In [4]:
AHR_Master = pd.read_csv('../../99_mm39_AHR_Enrichment/02_CleanUp_BED_File/AHR_Binding_Counts.txt', 
                            delimiter = '\t')

AHR_Master = AHR_Master.rename(columns={'gene_name': 'Gene', 'count': 'AHR'})

AHR_Master.head(5)

       Gene   AHR
0       NaN  2652
1  lnc10851   153
2   lnc7308    51
3     Hjurp    44
4   lnc3293    43

In [5]:
Annotations_Master = pd.read_csv('../../00_Karri_et_al_GTF/MGI_and_Karri_Annotations_Restructured_mm39.txt', 
                                              delimiter = '\t')

Annotations_Master = Annotations_Master.rename(columns={'mgi_symbol': 'MGI_Symbol',
                                                       'gene_biotype': 'Type'})

Annotations_Master.head(5)

/tmp/local/51388227/ipykernel_3251170/4085587502.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  Annotations_Master = pd.read_csv('../../00_Karri_et_al_GTF/MGI_and_Karri_Annotations_Restructured_mm39.txt',

,chrom,start,end,blank,score,strand,source,feature,frame,mgi_chr,...,mgi_end,MGI_Symbol,mgi_score,mgi_strand,gene_id,transcript_id,gene_name,Type,NR_annotation,NR_annotation2
0,chr1,3224554,3224816,.,1000,-,Genebody_mm10_lnc48261,exon,.,.,...,-1,.,-1,.,lnc_inter_chr1_15560,lnc_inter_chr1_15560,lnc15560,lncRNA,lnc15560,NaN
1,chr1,3273138,3274559,.,1000,-,Genebody_mm10_lnc48261,exon,.,.,...,-1,.,-1,.,lnc_inter_chr1_15561,lnc_inter_chr1_15561,lnc15561,lncRNA,lnc15561,NaN
2,chr1,3275710,3276991,.,1000,-,Genebody_mm10_lnc48261,exon,.,.,...,-1,.,-1,.,lnc_inter_chr1_15562,lnc_inter_chr1_15562,lnc15562,lncRNA,lnc15562,NaN
3,chr1,3284704,3741721,.,1000,-,GB_RefseqNM19801,exon,.,chr1,...,3729127,Gm19938,1000,-,Xkr4,Xkr4,Xkr4,NM,NaN,NaN
4,chr1,3536809,3583776,.,1000,+,EnsmblNR4698,exon,.,chr1,...,3583776,Gm1992,1000,+,Gm1992,Gm1992,Gm1992,antisense,NaN,NaN

In [6]:
directory = './Deseq2_Results/'

Deseq2_0_03_v_0 = pd.read_csv(directory + '0.03_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_0_1_v_0 = pd.read_csv(directory + '0.1_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_0_3_v_0 = pd.read_csv(directory + '0.3_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_1_v_0 = pd.read_csv(directory + '1_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_3_v_0 = pd.read_csv(directory + '3_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_10_v_0 = pd.read_csv(directory + '10_vs_0.txt', delimiter = '\t').reset_index()
Deseq2_30_v_0 = pd.read_csv(directory + '30_vs_0.txt', delimiter = '\t').reset_index()

In [7]:
Deseq2_0_03_v_0['Dose'] = '0.03'
Deseq2_0_1_v_0['Dose'] = '0.1'
Deseq2_0_3_v_0['Dose'] = '0.3'
Deseq2_1_v_0['Dose'] = '1'
Deseq2_3_v_0['Dose'] = '3'
Deseq2_10_v_0['Dose'] = '10'
Deseq2_30_v_0['Dose'] = '30'

In [8]:
Deseq2_10_v_0.head(5)

,index,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Dose
0,lnc_inter_chr1_100,0.738981,0.246277,2.463530,0.099969,0.920369,NaN,10
1,lnc_inter_chr1_1000,0.821042,-0.262164,2.064551,-0.126984,0.898953,NaN,10
2,lnc_as_chr11_10003,0.300701,1.832959,5.629859,0.325578,0.744744,NaN,10
3,lnc_as_chr11_10004,2.027109,3.473974,1.722713,2.016571,0.043740,0.141112,10
4,lnc_inter_chr11_10005,8.027321,-0.202391,0.591410,-0.342218,0.732187,0.868661,10

## <br> 3. Concat All Data Into One Dataframe

In [9]:
Deseq2_Master = pd.concat([Deseq2_0_03_v_0,
                          Deseq2_0_1_v_0,
                          Deseq2_0_3_v_0,
                          Deseq2_1_v_0,
                          Deseq2_3_v_0,
                          Deseq2_10_v_0,
                          Deseq2_30_v_0],
                          ignore_index=True)

In [10]:
Deseq2_Master = Deseq2_Master.rename(columns={'index': 'Gene'})
Deseq2_Master['FoldChange'] = pow(2, Deseq2_Master['log2FoldChange'])

Deseq2_Master.head(5)

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Dose,FoldChange
0,lnc_inter_chr1_100,0.738981,0.862954,2.429333,0.355223,0.722423,NaN,0.03,1.818759
1,lnc_inter_chr1_1000,0.821042,0.929693,1.989028,0.467411,0.640206,NaN,0.03,1.904871
2,lnc_as_chr11_10003,0.300701,0.000000,5.656128,0.000000,1.000000,NaN,0.03,1.000000
3,lnc_as_chr11_10004,2.027109,0.000000,1.904898,0.000000,1.000000,1.0,0.03,1.000000
4,lnc_inter_chr11_10005,8.027321,-0.269934,0.603792,-0.447065,0.654828,1.0,0.03,0.829357

In [11]:
# Merge Deseq2_Master with all metadata tables
Deseq2_Master2 = pd.merge(Deseq2_Master, Annotations_Master, left_on='Gene', right_on='gene_id', how='left').fillna("NA")

Deseq2_Master2.head(5)

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Dose,FoldChange,chrom,...,mgi_end,MGI_Symbol,mgi_score,mgi_strand,gene_id,transcript_id,gene_name,Type,NR_annotation,NR_annotation2
0,lnc_inter_chr1_100,0.738981,0.862954,2.429333,0.355223,0.722423,NA,0.03,1.818759,chr1,...,-1,.,-1,.,lnc_inter_chr1_100,lnc_inter_chr1_100,lnc100,lncRNA,lnc100,NA
1,lnc_inter_chr1_1000,0.821042,0.929693,1.989028,0.467411,0.640206,NA,0.03,1.904871,chr1,...,191154841,Gm32128,1000,+,lnc_inter_chr1_1000,lnc_inter_chr1_1000,lnc1000,lncRNA,lnc1000,NA
2,lnc_as_chr11_10003,0.300701,0.000000,5.656128,0.000000,1.0,NA,0.03,1.000000,chr11,...,94900160,Gm51875,1000,-,lnc_as_chr11_10003,lnc_as_chr11_10003,lnc10003,lncRNA,lnc10003,NA
3,lnc_as_chr11_10003,0.300701,0.000000,5.656128,0.000000,1.0,NA,0.03,1.000000,chr11,...,94900743,Gm36385,1000,-,lnc_as_chr11_10003,lnc_as_chr11_10003,lnc10003,lncRNA,lnc10003,NA
4,lnc_as_chr11_10004,2.027109,0.000000,1.904898,0.000000,1.0,1.0,0.03,1.000000,chr11,...,95049873,Dlx4os,1000,+,lnc_as_chr11_10004,lnc_as_chr11_10004,lnc10004,lncRNA,lnc10004_Dlx4os,Dlx4os

In [12]:
# Drop the 'Gene' column
Deseq2_Master2 = Deseq2_Master2.drop(columns=['Gene'])

Deseq2_Master2 = Deseq2_Master2.rename(columns={'gene_name': 'Gene'})
Deseq2_Master2 = Deseq2_Master2.rename(columns={'FoldChange': 'Fold-Change'})
Deseq2_Master2 = Deseq2_Master2.rename(columns={'log2FoldChange': 'Log2FC'})

Deseq2_Master2 = pd.merge(Deseq2_Master2, pDREs_Master, left_on='Gene', right_on='Gene', how='left').fillna(0)
Deseq2_Master2 = pd.merge(Deseq2_Master2, AHR_Master, left_on='Gene', right_on='Gene', how='left').fillna(0)

Deseq2_Master2[['pDRE', 'AHR']] = Deseq2_Master2[['pDRE', 'AHR']].astype(int)

Deseq2_Master_Working = Deseq2_Master2[['Gene', 'MGI_Symbol', 'Dose', 'pDRE', 'AHR', 'Type',  'baseMean',
                                      'Log2FC', 'Fold-Change', 'lfcSE', 'stat', 'pvalue', 'padj',
                                       'chrom', 'start', 'end', 'frame', 'score','strand',
                                        'gene_id', 'transcript_id', 'NR_annotation']].drop_duplicates(keep='first')

Deseq2_Master_Working

,Gene,MGI_Symbol,Dose,pDRE,AHR,Type,baseMean,Log2FC,Fold-Change,lfcSE,...,padj,chrom,start,end,frame,score,strand,gene_id,transcript_id,NR_annotation
0,lnc100,.,0.03,1,0,lncRNA,0.738981,0.862954,1.818759,2.429333,...,NA,chr1,21246734,21250265,.,1000,+,lnc_inter_chr1_100,lnc_inter_chr1_100,lnc100
1,lnc1000,Gm32128,0.03,0,8,lncRNA,0.821042,0.929693,1.904871,1.989028,...,NA,chr1,191152395,191156841,.,1000,+,lnc_inter_chr1_1000,lnc_inter_chr1_1000,lnc1000
2,lnc10003,Gm51875,0.03,0,0,lncRNA,0.300701,0.000000,1.000000,5.656128,...,NA,chr11,94897782,94903363,.,1000,-,lnc_as_chr11_10003,lnc_as_chr11_10003,lnc10003
3,lnc10003,Gm36385,0.03,0,0,lncRNA,0.300701,0.000000,1.000000,5.656128,...,NA,chr11,94897782,94903363,.,1000,-,lnc_as_chr11_10003,lnc_as_chr11_10003,lnc10003
4,lnc10004,Dlx4os,0.03,1,0,lncRNA,2.027109,0.000000,1.000000,1.904898,...,1.0,chr11,95035841,95050060,.,1000,+,lnc_as_chr11_10004,lnc_as_chr11_10004,lnc10004_Dlx4os
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365969,mt-Nd4l,.,30,0,0,mitochondrial protein-coding gene,28.894681,-0.353649,0.782602,0.350916,...,0.461948,chrM,9876,10173,.,.,+,ENSMUSG00000065947,ENSMUSG00000065947,NA
365970,mt-Nd4,.,30,0,0,mitochondrial protein-coding gene,98368.928940,-0.549831,0.683100,0.082421,...,0.0,chrM,10166,11544,.,.,+,ENSMUSG00000064363,ENSMUSG00000064363,NA
365971,mt-Nd5,.,30,0,0,mitochondrial protein-coding gene,67723.157378,-0.101532,0.932043,0.100825,...,0.462225,chrM,11741,13565,.,.,+,ENSMUSG00000064367,ENSMUSG00000064367,NA
365972,mt-Nd6,.,30,0,0,mitochondrial protein-coding gene,19830.183491,0.154663,1.113162,0.185883,...,0.556118,chrM,13551,14070,.,.,-,ENSMUSG00000064368,ENSMUSG00000064368,NA
365973,mt-Cytb,.,30,0,0,mitochondrial protein-coding gene,169173.377707,-0.665665,0.630398,0.084196,...,0.0,chrM,14144,15288,.,.,+,ENSMUSG00000064370,ENSMUSG00000064370,NA

In [13]:
Deseq2_Master_Working.to_csv('./RDDR_Deseq2_Master_Wald_Bulk_Mouse_with_Mouse_MGI.txt', sep='\t')